### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [byronknoll/gmix#1]
Every time I try to train using the `-t` function it just spits out the help menu no matter which files I choose in the command. How do I properly use the train function?

**Comment by jreoka** [comment]
I tried on a windows compiled binary and also on ubuntu. same issue sadly

**Comment by byronknoll** [comment]
Thanks for reporting. Can you paste the full command that you ran? You can try running with two additional arguments, like: `gmix -t file1 file2` (both file1 and file2 should already exist).

**Comment by jreoka** [comment]
Thats exactly what I ran. I tried running on 2 json files, and I even tried running on 2 files that didn't exist as well, just to see if it would do anything. It just outputs the help menu in both cases.

**Comment by jreoka** [comment]
Sorry to ask a favor but could you include a windows exe of gmix in the releases. Its super easy to build on linux but on Windows I really struggle to build the binary.

**Comment by byronknoll** [comment]
OK, I think I fixed the problem you encountered with -t. If you compile from the latest source, it should work. I also uploaded "gmix-v1-windows.zip" to the "v1" release on github.

**Comment by jreoka** [comment]
Thank you so much!
