### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by dillfrescott** [byronknoll/gmix#3]
The model files you get after training on data: the long file is a long term network and the short one is a short term network, correct? Or are they something different entirely?

**Comment by byronknoll** [comment]
It is "long term memory" and "short term memory". There are some comments describing them here:
https://github.com/byronknoll/gmix/blob/main/src/model.h#L7-L15
https://github.com/byronknoll/gmix/blob/main/src/memory/short-term-memory.h#L15-L18

**Comment by jreoka** [comment]
Noted. Thank you sir!

**Comment by jreoka** [comment]
So inferencing with short and long will give the same results. and the larger long term checkpoints are just for finetuning purposes?

**Comment by byronknoll** [comment]
Ah, a "checkpoint" is the combination of both files (you specify just the prefix when using the command line argument). The separation of the two files is just some internal implementation detail.

When inference (a.k.a. generation) happens, long term memory remains frozen. When training happens, long term memory gets updated.

**Comment by jreoka** [comment]
Ohhh okay gotcha. Thanks for clarifying!
